# -*- coding: utf-8 -*-
"""app1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fbkSd_QRdtIRfHpUs93PS0kd8mzV3pJE
"""

!pip -q install -U streamlit pandas numpy plotly openpyxl google-genai

import os
from getpass import getpass

GEMINI_API_KEY = getpass("Enter your Gemini API Key: ")

os.environ["GEMINI_API_KEY"] = GEMINI_API_KEY

print("✅ Gemini API key configured.")

from google import genai

client = genai.Client(
    api_key=os.environ["GEMINI_API_KEY"]
)

response = client.models.generate_content(
    model="gemini-3.6-flash",
    contents="Explain Generative AI in one simple sentence."
)

print(response.text)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import os
# import pandas as pd
# import numpy as np
# import streamlit as st
# import plotly.express as px
# 
# from google import genai
# 
# 
# # ============================================================
# # PAGE CONFIGURATION
# # ============================================================
# 
# st.set_page_config(
#     page_title="InsightAI - AI Data Analyst",
#     page_icon="🤖",
#     layout="wide"
# )
# 
# 
# # ============================================================
# # GEMINI CLIENT
# # ============================================================
# 
# API_KEY = os.getenv("GEMINI_API_KEY")
# 
# if not API_KEY:
# 
#     st.error(
#         "Gemini API key not found. "
#         "Please configure GEMINI_API_KEY."
#     )
# 
#     st.stop()
# 
# 
# client = genai.Client(
#     api_key=API_KEY
# )
# 
# 
# MODEL_NAME = "gemini-3.6-flash"
# 
# 
# # ============================================================
# # HELPER FUNCTIONS
# # ============================================================
# 
# def detect_date_columns(df):
# 
#     date_columns = []
# 
#     for column in df.columns:
# 
#         if pd.api.types.is_datetime64_any_dtype(
#             df[column]
#         ):
# 
#             date_columns.append(column)
# 
#             continue
# 
# 
#         if df[column].dtype in [
#             "object",
#             "string"
#         ]:
# 
#             try:
# 
#                 converted = pd.to_datetime(
#                     df[column],
#                     errors="coerce"
#                 )
# 
#                 valid_ratio = (
#                     converted.notna().mean()
#                 )
# 
#                 if valid_ratio >= 0.70:
# 
#                     date_columns.append(
#                         column
#                     )
# 
#             except Exception:
# 
#                 pass
# 
#     return date_columns
# 
# 
# def get_categorical_columns(df):
# 
#     return df.select_dtypes(
#         include=[
#             "object",
#             "string",
#             "category"
#         ]
#     ).columns.tolist()
# 
# 
# def create_dataset_summary(df):
# 
#     numeric_columns = (
#         df.select_dtypes(
#             include="number"
#         ).columns.tolist()
#     )
# 
#     categorical_columns = (
#         get_categorical_columns(df)
#     )
# 
#     summary = {
# 
#         "rows": len(df),
# 
#         "columns": len(df.columns),
# 
#         "numeric_columns":
#             numeric_columns,
# 
#         "categorical_columns":
#             categorical_columns,
# 
#         "missing_values":
#             int(
#                 df.isnull()
#                 .sum()
#                 .sum()
#             ),
# 
#         "duplicate_rows":
#             int(
#                 df.duplicated()
#                 .sum()
#             )
#     }
# 
#     return summary
# 
# 
# def generate_ai_insights(df):
# 
#     """
#     Send dataset information to Gemini
#     and generate business insights.
#     """
# 
#     # Limit data sent to AI
#     sample = df.head(30)
# 
#     summary = create_dataset_summary(
#         df
#     )
# 
#     statistics = ""
# 
#     numeric_columns = (
#         df.select_dtypes(
#             include="number"
#         ).columns.tolist()
#     )
# 
#     if numeric_columns:
# 
#         statistics = (
#             df[numeric_columns]
#             .describe()
#             .round(2)
#             .to_string()
#         )
# 
# 
#     prompt = f"""
# You are an expert AI Data Analyst.
# 
# Analyze the following dataset information.
# 
# Dataset summary:
# {summary}
# 
# Numerical statistics:
# {statistics}
# 
# Sample data:
# {sample.to_string(index=False)}
# 
# Provide a professional business analysis.
# 
# Include:
# 
# 1. Executive Summary
# 2. Key Findings
# 3. Important Trends
# 4. Potential Problems or Risks
# 5. Top Business Opportunities
# 6. Actionable Recommendations
# 
# Do not invent facts that are not supported by the dataset.
# 
# Use simple and professional language.
# """
# 
# 
#     response = client.models.generate_content(
# 
#         model=MODEL_NAME,
# 
#         contents=prompt
#     )
# 
#     return response.text
# 
# 
# def ask_ai_about_dataset(
#     df,
#     question
# ):
# 
#     sample = df.head(50)
# 
#     numeric_columns = (
#         df.select_dtypes(
#             include="number"
#         ).columns.tolist()
#     )
# 
#     statistics = ""
# 
#     if numeric_columns:
# 
#         statistics = (
#             df[numeric_columns]
#             .describe()
#             .round(2)
#             .to_string()
#         )
# 
# 
#     prompt = f"""
# You are an AI Data Analyst.
# 
# Answer the user's question using ONLY
# the provided dataset information.
# 
# Dataset shape:
# Rows: {len(df)}
# Columns: {len(df.columns)}
# 
# Column names:
# {list(df.columns)}
# 
# Numerical statistics:
# {statistics}
# 
# Sample dataset:
# {sample.to_string(index=False)}
# 
# User question:
# {question}
# 
# Instructions:
# 
# - Give a direct answer.
# - Explain your reasoning briefly.
# - Do not invent information.
# - If the dataset does not contain enough
#   information, clearly say so.
# - Use tables or bullet points when useful.
# """
# 
# 
#     response = client.models.generate_content(
# 
#         model=MODEL_NAME,
# 
#         contents=prompt
#     )
# 
#     return response.text
# 
# 
# def clean_dataset(df):
# 
#     cleaned = df.copy()
# 
# 
#     # Clean column names
# 
#     cleaned.columns = (
#         cleaned.columns
#         .astype(str)
#         .str.strip()
#     )
# 
# 
#     # Remove completely empty columns
# 
#     empty_columns = [
#         column
#         for column in cleaned.columns
#         if cleaned[column]
#         .isna()
#         .all()
#     ]
# 
# 
#     if empty_columns:
# 
#         cleaned = cleaned.drop(
#             columns=empty_columns
#         )
# 
# 
#     # Clean text columns
# 
#     text_columns = (
#         cleaned.select_dtypes(
#             include=[
#                 "object",
#                 "string"
#             ]
#         ).columns
#     )
# 
# 
#     for column in text_columns:
# 
#         cleaned[column] = (
#             cleaned[column]
#             .astype("string")
#             .str.strip()
#         )
# 
#         cleaned[column] = (
#             cleaned[column]
#             .replace(
#                 {
#                     "": pd.NA,
#                     "nan": pd.NA,
#                     "None": pd.NA,
#                     "null": pd.NA
#                 }
#             )
#         )
# 
# 
#     # Replace infinite values
# 
#     cleaned = cleaned.replace(
#         [
#             np.inf,
#             -np.inf
#         ],
#         np.nan
#     )
# 
# 
#     # Remove duplicates
# 
#     cleaned = (
#         cleaned.drop_duplicates()
#     )
# 
# 
#     return cleaned
# 
# 
# # ============================================================
# # TITLE
# # ============================================================
# 
# st.title(
#     "🤖 InsightAI"
# )
# 
# st.subheader(
#     "AI-Powered Data Analyst"
# )
# 
# st.write(
#     "Upload your dataset, explore the data, "
#     "and ask Gemini AI questions about your dataset."
# )
# 
# 
# st.divider()
# 
# 
# # ============================================================
# # FILE UPLOAD
# # ============================================================
# 
# st.header(
#     "📁 Upload Dataset"
# )
# 
# uploaded_file = st.file_uploader(
#     "Upload CSV or Excel file",
#     type=[
#         "csv",
#         "xlsx"
#     ]
# )
# 
# 
# if uploaded_file is None:
# 
#     st.info(
#         "👆 Upload a CSV or Excel dataset "
#         "to start analysis."
#     )
# 
#     st.stop()
# 
# 
# # ============================================================
# # LOAD DATA
# # ============================================================
# 
# try:
# 
#     if uploaded_file.name.lower().endswith(
#         ".csv"
#     ):
# 
#         try:
# 
#             df = pd.read_csv(
#                 uploaded_file,
#                 encoding="utf-8"
#             )
# 
#         except UnicodeDecodeError:
# 
#             uploaded_file.seek(0)
# 
#             df = pd.read_csv(
#                 uploaded_file,
#                 encoding="latin1"
#             )
# 
#     else:
# 
#         df = pd.read_excel(
#             uploaded_file
#         )
# 
# 
#     st.success(
#         f"✅ Dataset loaded: "
#         f"{uploaded_file.name}"
#     )
# 
# 
# except Exception as e:
# 
#     st.error(
#         f"Unable to load dataset: {e}"
#     )
# 
#     st.stop()
# 
# 
# # ============================================================
# # CLEAN DATA
# # ============================================================
# 
# if "cleaned_df" not in st.session_state:
# 
#     st.session_state[
#         "cleaned_df"
#     ] = df.copy()
# 
# 
# if st.button(
#     "🧹 Clean Dataset",
#     type="primary"
# ):
# 
#     st.session_state[
#         "cleaned_df"
#     ] = clean_dataset(df)
# 
#     st.success(
#         "✅ Dataset cleaned successfully!"
#     )
# 
# 
# cleaned_df = (
#     st.session_state[
#         "cleaned_df"
#     ]
# )
# 
# 
# # ============================================================
# # DATASET OVERVIEW
# # ============================================================
# 
# st.divider()
# 
# st.header(
#     "📊 Dataset Overview"
# )
# 
# 
# c1, c2, c3, c4 = st.columns(4)
# 
# 
# with c1:
# 
#     st.metric(
#         "Rows",
#         f"{len(cleaned_df):,}"
#     )
# 
# 
# with c2:
# 
#     st.metric(
#         "Columns",
#         f"{len(cleaned_df.columns):,}"
#     )
# 
# 
# with c3:
# 
#     st.metric(
#         "Missing Values",
#         f"{cleaned_df.isnull().sum().sum():,}"
#     )
# 
# 
# with c4:
# 
#     st.metric(
#         "Duplicate Rows",
#         f"{cleaned_df.duplicated().sum():,}"
#     )
# 
# 
# # ============================================================
# # DATA PREVIEW
# # ============================================================
# 
# st.subheader(
#     "👀 Dataset Preview"
# )
# 
# st.dataframe(
#     cleaned_df.head(10),
#     use_container_width=True
# )
# 
# 
# # ============================================================
# # NUMERICAL ANALYSIS
# # ============================================================
# 
# st.divider()
# 
# st.header(
#     "📈 Exploratory Data Analysis"
# )
# 
# 
# numeric_columns = (
#     cleaned_df.select_dtypes(
#         include="number"
#     ).columns.tolist()
# )
# 
# 
# categorical_columns = (
#     get_categorical_columns(
#         cleaned_df
#     )
# )
# 
# 
# if numeric_columns:
# 
#     st.subheader(
#         "📊 Numerical Statistics"
#     )
# 
#     statistics = (
#         cleaned_df[
#             numeric_columns
#         ]
#         .describe()
#         .T
#     )
# 
#     statistics["median"] = (
#         cleaned_df[
#             numeric_columns
#         ].median()
#     )
# 
#     statistics["missing"] = (
#         cleaned_df[
#             numeric_columns
#         ]
#         .isnull()
#         .sum()
#     )
# 
#     st.dataframe(
#         statistics.round(2),
#         use_container_width=True
#     )
# 
# 
# # ============================================================
# # KPI
# # ============================================================
# 
# st.subheader(
#     "🎯 Key Metrics"
# )
# 
# 
# if numeric_columns:
# 
#     metric_columns = st.columns(
#         min(
#             len(numeric_columns),
#             4
#         )
#     )
# 
# 
#     for i, column in enumerate(
#         numeric_columns[:4]
#     ):
# 
#         total = (
#             cleaned_df[column]
#             .sum()
#         )
# 
#         with metric_columns[i]:
# 
#             st.metric(
#                 column,
#                 f"{total:,.2f}"
#             )
# 
# 
# # ============================================================
# # VISUALIZATION
# # ============================================================
# 
# st.divider()
# 
# st.header(
#     "📊 Interactive Visualization"
# )
# 
# 
# if numeric_columns:
# 
#     selected_numeric = st.selectbox(
#         "Select numerical column",
#         numeric_columns
#     )
# 
# 
#     fig = px.histogram(
#         cleaned_df,
#         x=selected_numeric,
#         marginal="box",
#         title=(
#             f"Distribution of "
#             f"{selected_numeric}"
#         )
#     )
# 
# 
#     st.plotly_chart(
#         fig,
#         use_container_width=True
#     )
# 
# 
# if categorical_columns:
# 
#     selected_category = st.selectbox(
#         "Select categorical column",
#         categorical_columns
#     )
# 
# 
#     counts = (
#         cleaned_df[
#             selected_category
#         ]
#         .value_counts()
#         .head(15)
#         .reset_index()
#     )
# 
# 
#     counts.columns = [
#         selected_category,
#         "Count"
#     ]
# 
# 
#     fig = px.bar(
#         counts,
#         x=selected_category,
#         y="Count",
#         title=(
#             f"Top Categories — "
#             f"{selected_category}"
#         )
#     )
# 
# 
#     st.plotly_chart(
#         fig,
#         use_container_width=True
#     )
# 
# 
# # ============================================================
# # CORRELATION
# # ============================================================
# 
# if len(numeric_columns) >= 2:
# 
#     st.subheader(
#         "🔗 Correlation Analysis"
#     )
# 
# 
#     correlation = (
#         cleaned_df[
#             numeric_columns
#         ]
#         .corr()
#     )
# 
# 
#     st.dataframe(
#         correlation.round(2),
#         use_container_width=True
#     )
# 
# 
# # ============================================================
# # DATE ANALYSIS
# # ============================================================
# 
# st.divider()
# 
# st.header(
#     "📅 Date Analysis"
# )
# 
# 
# date_columns = (
#     detect_date_columns(
#         cleaned_df
#     )
# )
# 
# 
# if date_columns:
# 
#     selected_date = st.selectbox(
#         "Select date column",
#         date_columns
#     )
# 
# 
#     dates = pd.to_datetime(
#         cleaned_df[
#             selected_date
#         ],
#         errors="coerce"
#     ).dropna()
# 
# 
#     if not dates.empty:
# 
#         d1, d2, d3 = st.columns(3)
# 
# 
#         with d1:
# 
#             st.metric(
#                 "Earliest Date",
#                 dates.min().strftime(
#                     "%Y-%m-%d"
#                 )
#             )
# 
# 
#         with d2:
# 
#             st.metric(
#                 "Latest Date",
#                 dates.max().strftime(
#                     "%Y-%m-%d"
#                 )
#             )
# 
# 
#         with d3:
# 
#             st.metric(
#                 "Valid Records",
#                 f"{len(dates):,}"
#             )
# 
# 
# else:
# 
#     st.info(
#         "No date columns detected."
#     )
# 
# 
# # ============================================================
# # GENERATIVE AI BUSINESS ANALYSIS
# # ============================================================
# 
# st.divider()
# 
# st.header(
#     "🤖 Generative AI Business Analysis"
# )
# 
# 
# st.write(
#     "Gemini analyzes your dataset and generates "
#     "business insights using natural language."
# )
# 
# 
# if st.button(
#     "✨ Generate AI Insights",
#     type="primary"
# ):
# 
#     with st.spinner(
#         "Gemini is analyzing your dataset..."
#     ):
# 
#         try:
# 
#             ai_result = (
#                 generate_ai_insights(
#                     cleaned_df
#                 )
#             )
# 
# 
#             st.session_state[
#                 "ai_result"
#             ] = ai_result
# 
# 
#         except Exception as e:
# 
#             st.error(
#                 f"Gemini error: {e}"
#             )
# 
# 
# if "ai_result" in st.session_state:
# 
#     st.markdown(
#         st.session_state[
#             "ai_result"
#         ]
#     )
# 
# 
# # ============================================================
# # NATURAL LANGUAGE DATA ANALYST
# # ============================================================
# 
# st.divider()
# 
# st.header(
#     "💬 Ask Your Dataset"
# )
# 
# 
# st.write(
#     "Ask questions about your uploaded dataset "
#     "using natural language."
# )
# 
# 
# question = st.text_input(
#     "Example: Which category has the highest total?"
# )
# 
# 
# if st.button(
#     "🔎 Ask Gemini"
# ):
# 
#     if not question.strip():
# 
#         st.warning(
#             "Please enter a question."
#         )
# 
#     else:
# 
#         with st.spinner(
#             "Gemini is analyzing your question..."
#         ):
# 
#             try:
# 
#                 answer = (
#                     ask_ai_about_dataset(
#                         cleaned_df,
#                         question
#                     )
#                 )
# 
# 
#                 st.markdown(
#                     "### 🤖 Gemini Answer"
#                 )
# 
#                 st.markdown(
#                     answer
#                 )
# 
# 
#             except Exception as e:
# 
#                 st.error(
#                     f"Gemini error: {e}"
#                 )
# 
# 
# # ============================================================
# # RECOMMENDATIONS
# # ============================================================
# 
# st.divider()
# 
# st.header(
#     "💡 AI Recommendations"
# )
# 
# 
# if st.button(
#     "🚀 Generate Recommendations"
# ):
# 
#     with st.spinner(
#         "Generating recommendations..."
#     ):
# 
#         try:
# 
#             prompt = f"""
# You are a senior business analyst.
# 
# Analyze this dataset:
# 
# {cleaned_df.head(50).to_string(index=False)}
# 
# Dataset columns:
# {list(cleaned_df.columns)}
# 
# Provide 5 practical business recommendations.
# 
# Each recommendation should include:
# 
# 1. Observation
# 2. Business impact
# 3. Recommended action
# 
# Do not invent information.
# """
# 
# 
#             response = (
#                 client.models.generate_content(
#                     model=MODEL_NAME,
#                     contents=prompt
#                 )
#             )
# 
# 
#             st.markdown(
#                 response.text
#             )
# 
# 
#         except Exception as e:
# 
#             st.error(
#                 f"Gemini error: {e}"
#             )
# 
# 
# # ============================================================
# # DOWNLOAD
# # ============================================================
# 
# st.divider()
# 
# st.header(
#     "📥 Download Cleaned Dataset"
# )
# 
# 
# csv_data = (
#     cleaned_df
#     .to_csv(index=False)
#     .encode("utf-8")
# )
# 
# 
# st.download_button(
#     "📥 Download CSV",
#     csv_data,
#     "cleaned_dataset.csv",
#     "text/csv",
#     use_container_width=True
# )
# 
# 
# # ============================================================
# # FOOTER
# # ============================================================
# 
# st.divider()
# 
# st.caption(
#     "InsightAI | AI-Powered Data Analyst | "
#     "Python • Pandas • Plotly • Streamlit • Gemini"
# )

!streamlit run app.py --server.port 8501 --server.address 0.0.0.0 > /content/streamlit.log 2>&1 &

!cat /content/streamlit.log

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb

!cloudflared tunnel --url http://localhost:8501